CREATE TABLE tb_curso(
    id BIGSERIAL PRIMARY KEY,
    nome VARCHAR(150) NOT NULL UNIQUE
);

ALTER TABLE tb_solicitacao
ADD COLUMN curso_id BIGINT,
ADD CONSTRAINT fk_solicitacao_curso FOREIGN KEY(curso_id) REFERENCES tb_curso(id),
ADD COLUMN financeiro_ok BOOLEAN DEFAULT FALSE;

INSERT INTO tb_curso (nome) VALUES
 ('PRIMEIRO EMPREGO'),
 ('OPERADOR DE COMPUTADOR'),
 ('INFORMÁTICA KIDS'),
 ('PROGRAMADOR KIDS'),
 ('EMPREENDEDORISMO PARA EMPRESÁRIOS E FUTUROS LÍDERES'),
 ('ASSISTENTE ADMINISTRATIVO'),
 ('EXCEL AVANÇADO'),
 ('PROFISSIONAL DA SAÚDE'),
 ('DESIGNER GRÁFICO'),
 ('OPERADOR DE CAIXA'),
 ('ASSISTENTE CONTÁBIL'),
 ('ATENDIMENTO E VENDAS'),
 ('PROGRAMADOR DE COMPUTADOR'),
 ('DESENVOLVEDOR DE GAMES E APPS'),
 ('MARKETING DIGITAL'),
 ('INTELIGÊNCIA ARTIFICIAL'),
 ('SEGURANÇA DO TRABALHO'),
 ('INGLÊS ESSENCIAL'),
 ('INGLÊS AVANÇADO'),
 ('AUTOCAD PROJETISTA ALTO NÍVEL'),
 ('ASSISTENTE DE RECURSOS HUMANOS'),
 ('ASSISTENTE DE LOGÍSTICA');